name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build and Export
        run: npm run build
        env:
          NODE_ENV: production
        
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
